version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
       - SERVER_PORT=${SERVER_PORT}
       - IMMUDB_URL=${IMMUDB_URL}
       - IMMUDB_API_KEY=${IMMUDB_API_KEY}
