services:
  # Web service
  - type: web
    name: app
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SERVER_ADDRESS
        value: ${SERVER_ADDRESS}  
      - key: IMMUDB_ADDRESS
        value: ${IMMUDB_ADDRESS} 
      - key: IMMUDB_PORT
        value: ${IMMUDB_PORT}
      - key: IMMUDB_USERNAME
        value: ${IMMUDB_USERNAME}
      - key: IMMUDB_PASSWORD
        value: ${IMMUDB_PASSWORD}
    healthCheckPath: /health

  # ImmuDB service
  - type: pserv
    name: immudb
    runtime: image
    image:
      url: codenotary/immudb:latest
    disk:
      name: immudb-data
      mountPath: /var/lib/immudb
